# This file is generated by C:/repo/mingw-w64-python-numpy/src/numpy-py3-x86_64/setup.py
# It contains system_info results at the time of building this package.
__all__ = ["get_info","show"]

lapack_opt_info={'define_macros': [('HAVE_CBLAS', None)], 'language': 'c', 'library_dirs': ['C:/building/msys64/mingw64/lib'], 'libraries': ['openblas', 'openblas']}
blas_mkl_info={}
openblas_info={'define_macros': [('HAVE_CBLAS', None)], 'language': 'c', 'library_dirs': ['C:/building/msys64/mingw64/lib'], 'libraries': ['openblas', 'openblas']}
openblas_lapack_info={'define_macros': [('HAVE_CBLAS', None)], 'language': 'c', 'library_dirs': ['C:/building/msys64/mingw64/lib'], 'libraries': ['openblas', 'openblas']}
blas_opt_info={'define_macros': [('HAVE_CBLAS', None)], 'language': 'c', 'library_dirs': ['C:/building/msys64/mingw64/lib'], 'libraries': ['openblas', 'openblas']}

def get_info(name):
    g = globals()
    return g.get(name, g.get(name + "_info", {}))

def show():
    for name,info_dict in globals().items():
        if name[0] == "_" or type(info_dict) is not type({}): continue
        print(name + ":")
        if not info_dict:
            print("  NOT AVAILABLE")
        for k,v in info_dict.items():
            v = str(v)
            if k == "sources" and len(v) > 200:
                v = v[:60] + " ...\n... " + v[-60:]
            print("    %s = %s" % (k,v))
    