name: Run SiEPIC-Tool Layout tests 

on:
  workflow_dispatch:
  push:
    paths:
      - '**'
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - master


jobs:
  test_layouts:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

        # can also specify python version if needed
      - name: setup python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: install python 3.11 packages
        run: |
          pip install klayout numpy scipy pytest pytest-cov IPython
          pip install -e klayout_dot_config/python

      - name: Test with pytest, python 3.11
        run: pytest --cov=klayout_dot_config/python/SiEPIC --ignore=klayout_dot_config/python/SiEPIC/lumerical --ignore=klayout_dot_config/python/SiEPIC/tidy3d klayout_dot_config --cov-report=xml
      # run: pytest --cov=klayout_dot_config/python/SiEPIC klayout_dot_config/tech --cov-report=xml
  
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: github.repository_owner == 'SiEPIC'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true

      # - name: setup python 3.9
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.9'
      #     cache: "pip"
      #     cache-dependency-path: pyproject.toml

      # - name: install python 3.9 packages
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install klayout numpy scipy pytest pytest-cov

      # - name: Test with pytest, python 3.9
      #   run: pytest klayout_dot_config/tech
